on:
  workflow_dispatch:
  push:
  
permissions:
  id-token: write

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-region: eu-west-1
         role-to-assume: arn:aws:iam::084963261788:role/github-actions-oidc
      - run: 
         Install-Module -Name AWS.Tools.EC2 -Force
         Get-EC2Vpc
        shell: pwsh
      
