on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
         aws_region: us-west-2
         role-to-assume: arn:aws:iam::084963261788:role/github-actions-oidc
      - run: 
         Install-Modules -Name AWS.Tools.EC2 -Force
         Get-EC2Vpc
        shell: pwsh
      
